### ISSUE TITLE
[IX] Error if the extractor loses its linked property or template

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6985]
**Describe the bug**
In '/settings/metadata_extraction', an error occurs when you click the 'Review' button and the extractor no longer has a linked template.

**To Reproduce**
1. Create a new template with at least one property. 
2. Go to '/settings/metadata_extraction' and create a new extractor, linked to a property of this new template.
3. Come back to templates setting and delete this linked property or even the template.
4. Come back to '/settings/metadata_extraction'.
5. Click on 'Review' for this extractor.
6. You get an error:
![image](https://github.com/huridocs/uwazi/assets/73410334/78cc2ec1-8d98-4668-bdf4-5291a7d9d24f)

**Expected behavior**
This error should be avoided:
- If a property/template is linked to an extractor, then this property and its template must not be allowed to be deleted.
- Or if you prefer, if it remains posible to delete de property/template, then its 'Review' button on '/settings/metadata_extraction' should be hidden.

**Comment by aphilop** [comment]
@txau @RafaPolit 
In my opinion this should be priority high and should be fixed within the next sprints and while we are still developing the IX feature. The reported scenario apparently "brakes" the system.

**Comment by txau** [comment]
@aphilop I agree, Deleting a property should delete also the extractor and the associated data (labeled data etc)

**Comment by RafaPolit** [comment]
Since this is could have further implications, indeed we have decided to:
- Remove the property from the extractor (in case it has more than one and others still exist on the templates)
- Remove the whole extractor if all of its properties or templates or thesaurus are deleted
- Sanitize the suggestions that may have been using those values

**Comment by daneryl** [comment]
> * Remove the property from the extractor (in case it has more than one and others still exist on the templates)
> * Sanitize the suggestions that may have been using those values

This 2 were already implemented, the reason for the error was that the extractor is returned without templates and the client crashes.

> * Remove the whole extractor if all of its properties or templates or thesaurus are deleted

This is the only one that needs to be implemented to prevent the crash.

**Comment by aphilop** [comment]
Close as done.
