### ISSUE TITLE
For some reason the Thesauri translated into English are not showing the English version in report in English

### ISSUE THREAD

**Issue by Istamode** [huridocs/uwazidocs#8709]
Collection: https://syriahumanrightsreport.org/ 
The default language is Arabic

Thesauri /Governorate are translated from Arabic to English
But in the below report, the names of the cities is still in Arabic
https://syriahumanrightsreport.org/en/page/zabargnnudj/disappearance-report

**Comment by Istamode** [comment]
Should I create the Thesauri in English, then translate, even if my default language is Arabic?

**Comment by Istamode** [comment]
I am not quite sure if I have changed the default language at a certain point. Is it possible changing the default language might screw the Thesauri translation?

**Comment by Istamode** [comment]
A gentle follow-up on this request
Thanks
Adad

**Comment by RafaPolit** [comment]
Good morning Istamode.  We apologize for the late answer, office was closed for the year end holidays.

I would need a bit more for me understand the issue properly.  Pages need to be actually "translated" also, you would need to create HTML / code for each language.  They are not automatically translated.  If the values are showing correctly translated in the library, then your configuration and values are probably OK.

Can you please share screenshots of what you expect to work differently so we can understand your requirements better? The current link shows a page with an empty graph.

Thanks.

**Comment by Istamode** [comment]
Happy New Year. Thank you for the quick response. 

In the pages 
/page/edjxbzj1w4o/fatalities-report-ar
/page/edjxbzj1w4o/fatalities-report-en

In the section "Fatalities per Gender", the gender thesauri is not translated in the English version (attached are two screenshots)
Am I missing the point? Do I need to translate the data?

![Image](https://github.com/user-attachments/assets/25f93364-da43-4a69-932d-6ab41d529b93)
![Image](https://github.com/user-attachments/assets/5306320a-fad9-4772-a99f-d92cd0ad929e)

**Comment by RafaPolit** [comment]
Apparently your entities are not yet published (shared with the public) so, for me, the graphs appear empty.

However, there may be a misconception about translating pages.  You should probably not need to create page -en and page -ar.  The way to translate pages (and I see you already figured this out) is by changing the language of the UI and then changing the code of the HTML.  It will show the translated page, not by page name, but by changing the language required:

https://syrianalawiteshumanrights.org/en/page/edjxbzj1w4o/fatalities-report-ar
https://syrianalawiteshumanrights.org/ar/page/edjxbzj1w4o/fatalities-report-ar

I can see that your pages already show texts in English and Arabic correctly, so I'm assuming it's the charts that are the issue.  How are you getting the data for the charts? Can you post here the HTML you are using?

**Comment by Istamode** [comment]
Yes, it is private for now.
Right, I am aware that there is no need to rename the page for each language. I did it because I wanted to make sure I am editing the right version, as sometimes when changing the language, the previous language page will still be the active one to edit and I some times I modify the other language HTML without noticing. Could be the browser multi-tab issue.

Yes, right the issue is only in the graphs. It shows the values in one language.
Here is the section HTM in both En and Ar

<img width="628" height="169" alt="Image" src="https://github.com/user-attachments/assets/2198e7f1-9145-4a74-8db9-eea8de24db18" />


<img width="595" height="70" alt="Image" src="https://github.com/user-attachments/assets/82f737ae-452b-4610-a80b-f9e39cbfae23" />


<img width="1265" height="66" alt="Image" src="https://github.com/user-attachments/assets/d04facaa-46ed-4b40-a47c-78cde034eb16" />

**Comment by RafaPolit** [comment]
Thanks for the context.  I can replicate the error locally.  I believe this is a bug from our end when fetching the data from the dataset.  We are not respecting the UI language, nor can it be passed via the URL parameter.  We need to implement this.  Let me talk to the team and see how we can fit this into our pipeline.

cc @aphilop

**Comment by Istamode** [comment]
When defining the URL in the dataset, I could add the language, like:
 **/en**/library/?q=(allAggregations:!t,includeUnpublished:!t,order:desc,sort:creationDate,treatAs:number,unpublished:!f)

But this didn't resolve the issue

**Comment by Istamode** [comment]
I think there is a problem saving pages too, when switching between languages. I think having a different page name for each language is mandatory to avoid over-saving pages of different languages
I have just noticed that one of the pages, which had an English HTML, has been replaced with the Arabic version.

**Comment by Istamode** [comment]
Any ETA for solving the issue?

**Comment by aphilop** [comment]
Hi @Istamode,
We will further investigate this issue to find the root cause and provide a resolution in our upcoming sprint starting next week Tuesday, but I cannot provide any concrete time when this will be finished (depends on the findings of the investigation). We will further provide updates here when available. Thanks for your patience.

**Comment by RafaPolit** [comment]
@Istamode We will work on a fix for the non-translated values on the Dataset requests during the next few days.

We have checked the issue about requiring to change the page name as "mandatory" and could not reproduce the issue, this seems to be working as expected: the first save of a page duplicates the value in all languages, and any save after that is modifying only the current UI language.  It's not the best solution probably, but we are not seeing this issue of overwriting other languages if the name is not changed.  If you could provide more info in a different issue, it would be great.

**Comment by Istamode** [comment]
Thank you for the update on the non-translated values on the Dataset. I
will be waiting for it.
For the page save issue. It is difficult to reproduce. I let you know in a
separate ticket if I was able to provide retro steps

Thanks
Adad

**Comment by daneryl** [comment]
@Istamode the issue should be fixed, let us know if you encounter any problem.

**Comment by Istamode** [comment]
I could see that it is translating. I have a few values that are still not.
I need to verify if I need to change the data

Thanks
Adad
